EE_Scripts_es_debug = true;
EE_Scripts_es_weapon = [
    [], //Level 0
    [["arifle_Mk20_plain_F"]], //Level 1
    [], //Level 2
    [["LMG_mas_m72_F"]], //Level 3
    [["srifle_mas_sr25_v"]], //Level 4
    [["arifle_MX_F","arifle_MX_Black_F"],["arifle_MXC_F","arifle_MXC_Black_F"]], //Level 5
    [["srifle_DMR_01_F"]], //Level 6
    [["hgun_P07_F"],["mas_launch_RPG7_F"]], //Level 7
    [["srifle_mas_ebr"]], //Level 8
    [["LMG_Mk200_F"]], //Level 9
    [["arifle_mas_g36c"],["arifle_TRG21_F"],["arifle_TRG20_F"]], //Level 10
    [["rhs_weap_M136"]], //Level 11
    [["arifle_mas_m70"],["rhs_weap_M136_hedp"]], //Level 12
    [["arifle_MXM_F","arifle_MXM_Black_F"],["rhs_weap_M136_hp"]], //Level 13
    [["arifle_Katiba_C_F"],["arifle_Katiba_F"],["hgun_mas_grach_F"]], //Level 14
    [["arifle_Mk20_GL_plain_F"],["arifle_mas_m27m","arifle_mas_m27m_d","arifle_mas_m27m_v"]], //Level 15
    [["srifle_mas_hk417","srifle_mas_hk417_d","srifle_mas_hk417_v"]], //Level 16
    [["arifle_MX_GL_F","arifle_MX_GL_Black_F"],["rhs_weap_m16a4_carryhandle","rhs_weap_m16a4_carryhandle_grip","rhs_weap_m16a4_carryhandle_M203"]], //Level 17
    [["arifle_SDAR_F"],["mas_launch_LAW_F"]], //Level 18
    [["LMG_mas_M249_F","LMG_mas_M249_F_d","LMG_mas_M249_F_v"]], //Level 19
    [["rhs_weap_m4a1_carryhandle","arifle_mas_m4_d","arifle_mas_m4_v"],["rhs_weap_m4a1_carryhandle_grip2","rhs_weap_m4a1_carryhandle_grip","arifle_mas_m4c_d","arifle_mas_m4c_v"]], //Level 20
    [["srifle_mas_m91"]], //Level 21
    [["arifle_Katiba_GL_F"],["mas_launch_maaws_F"]], //Level 22
    [["arifle_TRG21_GL_F"],["hgun_Pistol_heavy_01_F"]], //Level 23
    [["srifle_mas_sr25","srifle_mas_sr25_d","srifle_mas_sr25_v"]], //Level 24
    [["arifle_mas_hk416","arifle_mas_hk416_d","arifle_mas_hk416_v"],["arifle_mas_hk416c","arifle_mas_hk416c_v","arifle_mas_hk416c_d"]], //Level 25
    [["LMG_mas_pkm_F","LMG_mas_pech_F"]], //Level 26
    [["arifle_mas_m70_gl"],["rhs_weap_smaw_green"]], //Level 27
    [["rhs_weap_XM2010","rhs_weap_XM2010_wd","rhs_weap_XM2010_d","rhs_weap_XM2010_sa"]], //Level 28
    [["hgun_mas_glocksf_F"]], //Level 29
    [["arifle_mas_mk16"],["arifle_mas_mk16_l"]], //Level 30
    [["MMG_01_hex_F","MMG_01_tan_F"]], //Level 31
    [["rhs_weap_sr25_ec","rhs_weap_sr25"]], //Level 32
    [["rhs_weap_m4a1_carryhandle_m203","rhs_weap_m4_m320","arifle_mas_m4_m203_d","arifle_mas_m4_m203_v"]], //Level 33
    [["hgun_mas_uzi_F"],["launch_B_Titan_F"]], //Level 34
    [["rhs_weap_m16a4_carryhandle","rhs_weap_m16a4_carryhandle_grip","rhs_weap_m16a4_carryhandle_M203"],["LMG_mas_mk48_F","LMG_mas_mk48_F_d","LMG_mas_mk48_F_v"]], //Level 35
    [["srifle_mas_mk17s"],["srifle_mas_m110"]], //Level 36
    [["arifle_mas_hk416_m203c","arifle_mas_hk416_m203c_d","arifle_mas_hk416_m203c_v"]], //Level 37
    [["launch_O_Titan_short_F"]], //Level 38
    [["srifle_DMR_05_blk_F","srifle_DMR_05_hex_F","srifle_DMR_05_tan_f"]], //Level 39
    [["srifle_DMR_03_spotter_F","srifle_DMR_03_tan_F","srifle_DMR_03_woodland_F","srifle_DMR_03_khaki_F"],["rhs_weap_m249_pip_L","rhs_weap_m249_pip_L_vfg"]], //Level 40
    [["srifle_mas_sr25","srifle_mas_sr25_d","srifle_mas_sr25_v","srifle_mas_sr25_v"]], //Level 41
    [["srifle_DMR_02_F","srifle_DMR_02_camo_F","srifle_DMR_02_sniper_F"]], //Level 42
    [["srifle_DMR_03_khaki_F","arifle_mas_mk16_gl"]], //Level 43
    [["LMG_mas_m240_F"],["hgun_Pistol_heavy_02_F"],["rhs_weap_fim92"]], //Level 44
    [["FHQ_arifle_ACR_blk","FHQ_arifle_ACR_snw","FHQ_arifle_ACR_tan","FHQ_arifle_ACR_wdl"]], //Level 45
    [["srifle_DMR_03_spotter_F","srifle_DMR_03_tan_F","srifle_DMR_03_woodland_F","srifle_DMR_03_khaki_F"]], //Level 46
    [["rhs_weap_m16a4_carryhandle_M203"],["rhs_weap_fgm148"]], //Level 47
    [["arifle_mas_akm"],["arifle_mas_akm_gl"]], //Level 48
    [["arifle_mas_m4vlt"],["MMG_02_black_F","MMG_02_camo_F","MMG_02_sand_F"]], //Level 49
    [["srifle_mas_mk17"],["arifle_mas_mk17_gl"],["srifle_GM6_F","srifle_GM6_camo_F"],["hgun_mas_mp7p_F"]] //Level 50
  ];
EE_Scripts_es_backpack =
  [
  	[], //Level 0
  	[], //Level 1
  	[], //Level 2
  	[], //Level 3
  	[], //Level 4
  	[["MC_Backpack_Compact","MarPat_Backpack_Compact"]], //Level 5
  	[], //Level 6
  	[], //Level 7
  	[["AOR1_Backpack_Compact","Project_Honor_Backpack_Compact"]], //Level 8
  	[], //Level 9
  	[["MC_Backpack_Kitbag","MarPat_Backpack_Kitbag"]], //Level 10
  	[], //Level 11
  	[["ABU_Backpack_Compact","B_mas_AssaultPack_black"]], //Level 12
  	[], //Level 13
  	[["AOR1_Backpack_Kitbag","Project_Honor_Backpack_Kitbag"]], //Level 14
  	[], //Level 15
  	[["ACE_NonSteerableParachute"]], //Level 16
  	[], //Level 17
  	[["B_Parachute"]], //Level 18
  	[], //Level 19
  	[["B_UAV_01_backpack_F"]], //Level 20
  	[], //Level 21
  	[["ABU_Backpack_Kitbag","B_mas_Kitbag_black"]], //Level 22
  	[], //Level 23
  	[], //Level 24
  	[], //Level 25
  	[], //Level 26
  	[], //Level 27
  	[], //Level 28
  	[], //Level 29
  	[], //Level 30
  	[], //Level 31
  	[], //Level 32
  	[], //Level 33
  	[], //Level 34
  	[], //Level 35
  	[], //Level 36
  	[], //Level 37
  	[], //Level 38
  	[], //Level 39
  	[], //Level 40
  	[], //Level 41
  	[], //Level 42
  	[], //Level 43
  	[], //Level 44
  	[], //Level 45
  	[], //Level 46
  	[], //Level 47
  	[], //Level 48
  	[], //Level 49
  	[] //Level 50
  ];
EE_Scripts_es_item =
  [
  	[["optic_Aco"]], //Level 0
  	[["MC_Helmet2","MarPat_Helmet2","AOR1_Helmet2","Project_Honor_Helmet2","ABU_Helmet2","MCB_Helmet2"]], //Level 1
  	[["MC_Cap","MarPat_Cap","AOR1_Cap","Project_Honor_Cap","ABU_Cap","MCB_Cap"]], //Level 2
  	[["MC_Vest_3","MarPat_Vest_3","AOR1_Vest_3","Project_Honor_Vest_3","ABU_Vest_3","MCB_Vest_3"]], //Level 3
  	[["MC_Boonie","MarPat_Boonie","AOR1_Boonie","Project_Honor_Boonie","ABU_Boonie","MCB_Boonie"]], //Level 4
  	[["G_Shades_Black","G_Shades_Blue","G_Shades_Green","G_Shades_Red"]], //Level 5
  	[["optic_Holosight","optic_mas_Holosight_blk","optic_mas_Holosight_camo"]], //Level 6
  	[["G_mas_wpn_gog"],["optic_SOS"]], //Level 7
  	[["FHQ_optic_HWS","FHQ_optic_HWS_tan"],["acc_flashlight","acc_mas_flash_gun"]], //Level 8
  	[["G_Lowprofile"],["optic_Hamr","FHQ_optic_AIM","FHQ_optic_AIM_tan"]], //Level 9
  	[["FHQ_optic_MicroCCO","FHQ_optic_MicroCCO_tan"],["FHQ_optic_MARS","FHQ_optic_MARS_tan"]], //Level 10
  	[["MC_Vest_2","MarPat_Vest_2","AOR1_Vest_2","Project_Honor_Vest_2","ABU_Vest_2","MCB_Vest_2"]], //Level 11
  	[["MC_Helmet1","MarPat_Helmet1","AOR1_Helmet1","Project_Honor_Helmet1","ABU_Helmet1","MCB_Helmet1"]], //Level 12
  	[["G_mas_wpn_mask_b","G_mas_wpn_mask"],["optic_KHS_blk","optic_KHS_tan"]], //Level 13
  	[["ACE_NVG_Gen1"],["optic_MRCO","optic_mas_aim","optic_mas_aim_c"]], //Level 14
  	[["U_B_GhillieSuit"],["FHQ_optic_ACOG","FHQ_optic_ACOG_tan"]], //Level 15
  	[["rhsusf_iotv_ocp","rhsusf_iotv_ucp"],["optic_Yorris","optic_MRD"]], //Level 16
  	[["G_Tactical_Clear"],["U_I_GhillieSuit"]], //Level 17
  	[["rhsusf_ach_helmet_ocp","rhsusf_ach_helmet_ucp","rhsusf_lwh_helmet_marpatd","rhsusf_lwh_helmet_marpatwd"]], //Level 18
  	[["ACE_NVG_Gen2"],["bipod_01_F_blk","bipod_01_F_snd"]], //Level 19
  	[["H_HelmetB_camo"],["optic_Arco","optic_mas_acog_eo","optic_mas_acog_rd_c"]], //Level 20
  	[["MC_Vest_4","MarPat_Vest_4","AOR1_Vest_4","Project_Honor_Vest_4","ABU_Vest_4","MCB_Vest_4"]], //Level 21
  	[["G_mas_wpn_shemag"],["FHQ_optic_MCCO_M_BLK","FHQ_optic_MCCO_M_TAN"]], //Level 22
  	[["G_mas_wpn_wrap_t","G_mas_wpn_wrap_b"]], //Level 23
  	[["NVGoggles"],["optic_DMS"]], //Level 24
  	[["G_mas_wpn_wrap_mask_b","G_mas_wpn_wrap_mask_t"],["FHQ_optic_HWS_G33","FHQ_optic_HWS_G33_tan"]], //Level 25
  	[["rhsusf_iotv_ocp_Rifleman","rhsusf_iotv_ucp_Rifleman"],["muzzle_mas_snds_C","muzzle_snds_L"]], //Level 26
  	[["G_mas_wpn_shemag_mask"],["U_B_FullGhillie_ard"],["FHQ_acc_ANPEQ15_black","FHQ_acc_ANPEQ15"]], //Level 27
  	[["rhsusf_ach_helmet_ESS_ocp","rhsusf_ach_helmet_ESS_ucp","rhsusf_lwh_helmet_marpatd_ess","rhsusf_lwh_helmet_marpatwd_blk_ess"]], //Level 28
  	[["ACE_NVG_Gen4"],["optic_AMS","optic_AMS_snd"]], //Level 29
  	[["G_Combat"],["FHQ_optic_AimM_BLK","FHQ_optic_AimM_TAN"]], //Level 30
  	[["MC_Vest_1","MarPat_Vest_1","AOR1_Vest_1","Project_Honor_Vest_1","ABU_Vest_1","MCB_Vest_1"]], //Level 31
  	[["G_Balaclava_blk","G_Balaclava_oli"],["muzzle_snds_M","FHQ_muzzle_snds_68SPC"]], //Level 32
  	[["V_PlateCarrierGL_blk","V_PlateCarrierGL_rgr"],["rhs_acc_1pn93_1"]], //Level 33
  	[["ACE_NVG_Wide"],["rhsusf_acc_SR25S"]], //Level 34
  	[["G_mas_wpn_wrap_c","G_mas_wpn_wrap_mask_c"],["optic_NVS"]], //Level 35
  	[["rhsusf_iotv_ocp_Repair","rhsusf_iotv_ucp_Repair"],["muzzle_snds_H","muzzle_snds_H_MG"]], //Level 36
  	[["G_Balaclava_lowprofile"],["optic_tws","optic_tws_mg"]], //Level 37
  	[["rhsusf_ach_helmet_headset_ess_ocp","rhsusf_ach_helmet_headset_ess_ucp","rhsusf_lwh_helmet_marpatd_headset","rhsusf_lwh_helmet_marpatwd_headset_blk"]], //Level 38
  	[["G_Balaclava_combat"],["FHQ_optic_TWS3050","FHQ_optic_VCOG","FHQ_optic_VCOG_tan"]], //Level 39
  	[["U_B_FullGhillie_lsh"],["FHQ_acc_LLM01F","acc_pointer_IR","ACE_acc_pointer_green"]], //Level 40
  	[["MC_Vest_1","MarPat_Vest_1","AOR1_Vest_1","Project_Honor_Vest_1","ABU_Vest_1","MCB_Vest_1"]], //Level 41
  	[["G_mas_wpn_bala_b"]], //Level 42
  	[["optic_Nightstalker"]], //Level 43
  	[["optic_LRPS"],["muzzle_snds_93mmg","muzzle_snds_93mmg_tan"]], //Level 44
  	[["G_Bandanna_aviator"]], //Level 45
  	[["rhsusf_iotv_ocp_Teamleader","rhsusf_iotv_ocp_Teamleader"]], //Level 46
  	[["FHQ_optic_LeupoldERT","FHQ_optic_LeupoldERT_tan"]], //Level 47
  	[], //Level 48
  	[["V_PlateCarrierIAGL_oli","V_PlateCarrierIAGL_dgtl"]], //Level 49
  	[["muzzle_snds_338_black","muzzle_snds_338_sand"]] //Level 50
  ];
